package cn.jboa.pojo;
// Generated 2018-4-12 9:45:45 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BizClaimVoucher generated by hbm2java
 */
@Entity
@Table(name = "biz_claim_voucher", catalog = "jboadb")
public class BizClaimVoucher implements java.io.Serializable {

	private long id;
	private SysEmployee sysEmployeeByNextDealSn;
	private SysEmployee sysEmployeeByCreateSn;
	private Date createTime;
	private String event;
	private BigDecimal totalAccount;
	private String status;
	private Date modifyTime;
	private Set<BizCheckResult> bizCheckResults = new HashSet<BizCheckResult>(0);
	private Set<BizClaimVoucherDetail> bizClaimVoucherDetails = new HashSet<BizClaimVoucherDetail>(0);

	public BizClaimVoucher() {
	}

	public BizClaimVoucher(long id, SysEmployee sysEmployeeByCreateSn, Date createTime, String event,
			BigDecimal totalAccount, String status) {
		this.id = id;
		this.sysEmployeeByCreateSn = sysEmployeeByCreateSn;
		this.createTime = createTime;
		this.event = event;
		this.totalAccount = totalAccount;
		this.status = status;
	}

	public BizClaimVoucher(long id, SysEmployee sysEmployeeByNextDealSn, SysEmployee sysEmployeeByCreateSn,
			Date createTime, String event, BigDecimal totalAccount, String status, Date modifyTime,
			Set<BizCheckResult> bizCheckResults, Set<BizClaimVoucherDetail> bizClaimVoucherDetails) {
		this.id = id;
		this.sysEmployeeByNextDealSn = sysEmployeeByNextDealSn;
		this.sysEmployeeByCreateSn = sysEmployeeByCreateSn;
		this.createTime = createTime;
		this.event = event;
		this.totalAccount = totalAccount;
		this.status = status;
		this.modifyTime = modifyTime;
		this.bizCheckResults = bizCheckResults;
		this.bizClaimVoucherDetails = bizClaimVoucherDetails;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NEXT_DEAL_SN")
	public SysEmployee getSysEmployeeByNextDealSn() {
		return this.sysEmployeeByNextDealSn;
	}

	public void setSysEmployeeByNextDealSn(SysEmployee sysEmployeeByNextDealSn) {
		this.sysEmployeeByNextDealSn = sysEmployeeByNextDealSn;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CREATE_SN", nullable = false)
	public SysEmployee getSysEmployeeByCreateSn() {
		return this.sysEmployeeByCreateSn;
	}

	public void setSysEmployeeByCreateSn(SysEmployee sysEmployeeByCreateSn) {
		this.sysEmployeeByCreateSn = sysEmployeeByCreateSn;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATE_TIME", nullable = false, length = 0)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "EVENT", nullable = false)
	public String getEvent() {
		return this.event;
	}

	public void setEvent(String event) {
		this.event = event;
	}

	@Column(name = "TOTAL_ACCOUNT", nullable = false, precision = 20)
	public BigDecimal getTotalAccount() {
		return this.totalAccount;
	}

	public void setTotalAccount(BigDecimal totalAccount) {
		this.totalAccount = totalAccount;
	}

	@Column(name = "STATUS", nullable = false, length = 20)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODIFY_TIME", length = 0)
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "bizClaimVoucher")
	public Set<BizCheckResult> getBizCheckResults() {
		return this.bizCheckResults;
	}

	public void setBizCheckResults(Set<BizCheckResult> bizCheckResults) {
		this.bizCheckResults = bizCheckResults;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "bizClaimVoucher")
	public Set<BizClaimVoucherDetail> getBizClaimVoucherDetails() {
		return this.bizClaimVoucherDetails;
	}

	public void setBizClaimVoucherDetails(Set<BizClaimVoucherDetail> bizClaimVoucherDetails) {
		this.bizClaimVoucherDetails = bizClaimVoucherDetails;
	}

	@Override
	public String toString() {
		return "BizClaimVoucher [id=" + id + ", sysEmployeeByNextDealSn=" + sysEmployeeByNextDealSn
				+ ", sysEmployeeByCreateSn=" + sysEmployeeByCreateSn + ", createTime=" + createTime + ", event=" + event
				+ ", totalAccount=" + totalAccount + ", status=" + status + ", modifyTime=" + modifyTime
				+ ", bizCheckResults=" + bizCheckResults + ", bizClaimVoucherDetails=" + bizClaimVoucherDetails + "]";
	}

}
