package cn.jboa.pojo;
// Generated 2018-4-12 9:45:45 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BizClaimVoucherStatistics generated by hbm2java
 */
@Entity
@Table(name = "biz_claim_voucher_statistics", catalog = "jboadb")
public class BizClaimVoucherStatistics implements java.io.Serializable {

	private long id;
	private SysDepartment sysDepartment;
	private BigDecimal totalCount;
	private long year;
	private long month;
	private Date modifyTime;

	public BizClaimVoucherStatistics() {
	}

	public BizClaimVoucherStatistics(long id, SysDepartment sysDepartment, BigDecimal totalCount, long year, long month,
			Date modifyTime) {
		this.id = id;
		this.sysDepartment = sysDepartment;
		this.totalCount = totalCount;
		this.year = year;
		this.month = month;
		this.modifyTime = modifyTime;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DEPARTMENT_ID", nullable = false)
	public SysDepartment getSysDepartment() {
		return this.sysDepartment;
	}

	public void setSysDepartment(SysDepartment sysDepartment) {
		this.sysDepartment = sysDepartment;
	}

	@Column(name = "TOTAL_COUNT", nullable = false, precision = 20)
	public BigDecimal getTotalCount() {
		return this.totalCount;
	}

	public void setTotalCount(BigDecimal totalCount) {
		this.totalCount = totalCount;
	}

	@Column(name = "YEAR", nullable = false)
	public long getYear() {
		return this.year;
	}

	public void setYear(long year) {
		this.year = year;
	}

	@Column(name = "MONTH", nullable = false)
	public long getMonth() {
		return this.month;
	}

	public void setMonth(long month) {
		this.month = month;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODIFY_TIME", nullable = false, length = 0)
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

}
