package cn.jboa.pojo;
// Generated 2018-4-12 9:45:45 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BizClaimVouyearStatistics generated by hbm2java
 */
@Entity
@Table(name = "biz_claim_vouyear__statistics", catalog = "jboadb")
public class BizClaimVouyearStatistics implements java.io.Serializable {

	private long id;
	private BigDecimal totalCount;
	private long year;
	private Date modifyTime;
	private long departmentId;

	public BizClaimVouyearStatistics() {
	}

	public BizClaimVouyearStatistics(long id, BigDecimal totalCount, long year, Date modifyTime, long departmentId) {
		this.id = id;
		this.totalCount = totalCount;
		this.year = year;
		this.modifyTime = modifyTime;
		this.departmentId = departmentId;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "TOTAL_COUNT", nullable = false, precision = 30)
	public BigDecimal getTotalCount() {
		return this.totalCount;
	}

	public void setTotalCount(BigDecimal totalCount) {
		this.totalCount = totalCount;
	}

	@Column(name = "YEAR", nullable = false)
	public long getYear() {
		return this.year;
	}

	public void setYear(long year) {
		this.year = year;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODIFY_TIME", nullable = false, length = 0)
	public Date getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	@Column(name = "DEPARTMENT_ID", nullable = false)
	public long getDepartmentId() {
		return this.departmentId;
	}

	public void setDepartmentId(long departmentId) {
		this.departmentId = departmentId;
	}

}
