package cn.jboa.pojo;
// Generated 2018-4-12 9:45:45 by Hibernate Tools 3.2.2.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BizCheckResult generated by hbm2java
 */
@Entity
@Table(name = "biz_check_result", catalog = "jboadb")
public class BizCheckResult implements java.io.Serializable {

	private long id;
	private BizClaimVoucher bizClaimVoucher;
	private Date checkTime;
	private SysEmployee checkerSn;
	private String result;
	private String comm;

	public BizCheckResult() {
	}

	public BizCheckResult(long id, BizClaimVoucher bizClaimVoucher, Date checkTime, SysEmployee checkerSn, String result,
			String comm) {
		this.id = id;
		this.bizClaimVoucher = bizClaimVoucher;
		this.checkTime = checkTime;
		this.checkerSn = checkerSn;
		this.result = result;
		this.comm = comm;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CLAIM_ID", nullable = false)
	public BizClaimVoucher getBizClaimVoucher() {
		return this.bizClaimVoucher;
	}

	public void setBizClaimVoucher(BizClaimVoucher bizClaimVoucher) {
		this.bizClaimVoucher = bizClaimVoucher;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CHECK_TIME", nullable = false, length = 0)
	public Date getCheckTime() {
		return this.checkTime;
	}

	public void setCheckTime(Date checkTime) {
		this.checkTime = checkTime;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CHECKER_SN", nullable = false)
	public SysEmployee getCheckerSn() {
		return this.checkerSn;
	}

	public void setCheckerSn(SysEmployee checkerSn) {
		this.checkerSn = checkerSn;
	}

	@Column(name = "RESULT", nullable = false, length = 50)
	public String getResult() {
		return this.result;
	}

	public void setResult(String result) {
		this.result = result;
	}

	@Column(name = "COMM", nullable = false, length = 500)
	public String getComm() {
		return this.comm;
	}

	public void setComm(String comm) {
		this.comm = comm;
	}

}
