package cn.jboa.pojo;
// Generated 2018-4-12 9:45:45 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BizLeave generated by hbm2java
 */
@Entity
@Table(name = "biz_leave", catalog = "jboadb")
public class BizLeave implements java.io.Serializable {

	private long id;
	private SysEmployee employeeSn;
	private Date starttime;
	private Date endtime;
	private BigDecimal leaveday;
	private String reason;
	private String status;
	private String leavetype;
	private SysEmployee nextDealSn;
	private String approveOpinion;
	private Date createtime;
	private Date modifytime;

	public BizLeave() {
	}

	public BizLeave(long id, SysEmployee employeeSn, Date starttime, Date endtime, BigDecimal leaveday, String reason) {
		this.id = id;
		this.employeeSn = employeeSn;
		this.starttime = starttime;
		this.endtime = endtime;
		this.leaveday = leaveday;
		this.reason = reason;
	}

	public BizLeave(long id, SysEmployee employeeSn, Date starttime, Date endtime, BigDecimal leaveday, String reason,
			String status, String leavetype, SysEmployee nextDealSn, String approveOpinion, Date createtime,
			Date modifytime) {
		this.id = id;
		this.employeeSn = employeeSn;
		this.starttime = starttime;
		this.endtime = endtime;
		this.leaveday = leaveday;
		this.reason = reason;
		this.status = status;
		this.leavetype = leavetype;
		this.nextDealSn = nextDealSn;
		this.approveOpinion = approveOpinion;
		this.createtime = createtime;
		this.modifytime = modifytime;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EMPLOYEE_SN")
	public SysEmployee getEmployeeSn() {
		return this.employeeSn;
	}

	public void setEmployeeSn(SysEmployee employeeSn) {
		this.employeeSn = employeeSn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "STARTTIME", nullable = false, length = 0)
	public Date getStarttime() {
		return this.starttime;
	}

	public void setStarttime(Date starttime) {
		this.starttime = starttime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ENDTIME", nullable = false, length = 0)
	public Date getEndtime() {
		return this.endtime;
	}

	public void setEndtime(Date endtime) {
		this.endtime = endtime;
	}

	@Column(name = "LEAVEDAY", nullable = false, precision = 5, scale = 1)
	public BigDecimal getLeaveday() {
		return this.leaveday;
	}

	public void setLeaveday(BigDecimal leaveday) {
		this.leaveday = leaveday;
	}

	@Column(name = "REASON", nullable = false, length = 500)
	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	@Column(name = "STATUS", length = 20)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "LEAVETYPE", length = 50)
	public String getLeavetype() {
		return this.leavetype;
	}

	public void setLeavetype(String leavetype) {
		this.leavetype = leavetype;
	}
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NEXT_DEAL_SN")
	public SysEmployee getNextDealSn() {
		return this.nextDealSn;
	}

	public void setNextDealSn(SysEmployee nextDealSn) {
		this.nextDealSn = nextDealSn;
	}

	@Column(name = "APPROVE_OPINION", length = 100)
	public String getApproveOpinion() {
		return this.approveOpinion;
	}

	public void setApproveOpinion(String approveOpinion) {
		this.approveOpinion = approveOpinion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATETIME", length = 0)
	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFYTIME", length = 0)
	public Date getModifytime() {
		return this.modifytime;
	}

	public void setModifytime(Date modifytime) {
		this.modifytime = modifytime;
	}

}
