package cn.jboa.pojo;
// Generated 2018-4-12 9:45:45 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SysDepartment generated by hbm2java
 */
@Entity
@Table(name = "sys_department", catalog = "jboadb")
public class SysDepartment implements java.io.Serializable {

	private long id;
	private String name;
	private Set<SysEmployee> sysEmployees = new HashSet<SysEmployee>(0);
	private Set<BizClaimVoucherStatistics> bizClaimVoucherStatisticses = new HashSet<BizClaimVoucherStatistics>(0);

	public SysDepartment() {
	}

	public SysDepartment(long id, String name) {
		this.id = id;
		this.name = name;
	}

	public SysDepartment(long id, String name, Set<SysEmployee> sysEmployees,
			Set<BizClaimVoucherStatistics> bizClaimVoucherStatisticses) {
		this.id = id;
		this.name = name;
		this.sysEmployees = sysEmployees;
		this.bizClaimVoucherStatisticses = bizClaimVoucherStatisticses;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "NAME", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "sysDepartment")
	public Set<SysEmployee> getSysEmployees() {
		return this.sysEmployees;
	}

	public void setSysEmployees(Set<SysEmployee> sysEmployees) {
		this.sysEmployees = sysEmployees;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "sysDepartment")
	public Set<BizClaimVoucherStatistics> getBizClaimVoucherStatisticses() {
		return this.bizClaimVoucherStatisticses;
	}

	public void setBizClaimVoucherStatisticses(Set<BizClaimVoucherStatistics> bizClaimVoucherStatisticses) {
		this.bizClaimVoucherStatisticses = bizClaimVoucherStatisticses;
	}

}
